spring:
  application:
    name: finches-sservice
  data:
    mongodb:
      host: localhost
      port: 27017
      username: supervisor
      password: root
      database: finches
server:
  port: 80

jwt:
  secret: USEITFEELIT
